### ISSUE TITLE
Typeahead doesnt work properly in component set to ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by slubowsky** [valor-software/ngx-bootstrap#1177]
If typeaheads are used in a component with changeDetection set to ChangeDetectionStrategy.OnPush the typeaheads dont behave properly. i.e. The UI is not always (e.g. on initial click) updated when the dropdown should be appearing. This problem only occurs when parent is set to ChangeDetectionStrategy.OnPush. When that is removed everything works as expected.

See https://github.com/valor-software/ng2-bootstrap/issues/563 and its fix https://github.com/valor-software/ng2-bootstrap/pull/566 which is likely exactly the same thing needed here. Perhaps call changeDetector.markForCheck() in both show() and hide()?

my work around for now is to call markForCheck whenever typeaheadLoading is fired :(

**Comment by valorkin** [comment]
hm, had to check this out

**Comment by diegomaninetti** [comment]
Same behavior for RadioButton (btnRadio) directive.

**Comment by olaf89** [comment]
I had the same issue, im using redux for state management, so my typeahead data is just array and is being updated each time after user keys in, 

The issue is when using on push strategy options are not updated, they are loaded but the visible options list is updated only after user type in.

so lets say user type in : 
A
and loaded options are: 
Ab
Abc
Abcd

They are hidden until he types in Ab.
at least that what it looks like.

After removal of onPush, it works fine.

**Comment by IlyaSurmay** [comment]
Hi, could you reproduce this issue in plunkr/stackblitz?
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by slubowsky** [comment]
@IlyaSurmay I no longer have this issue using 2.0.0-beta.8. I believe it was fixed for me at least some time ago but couldn't say exactly which version
