### ISSUE TITLE
Error in 'Alert' Documentation

### ISSUE THREAD

**Issue by woodrufs** [valor-software/ngx-bootstrap#1261]
Hi everyone,

Thanks for putting together this library! Your work is very much appreciated. I believe there is an error in the documentation, though. 

Link: http://valor-software.com/ng2-bootstrap/#/alerts
Issue: If I wrap the brackets around the directive type (as the example shows on this page), the alert type is not recognized. When using brackets, I am seeing the class 'alert-undefined' applied (instead of alert-success, alert-warning, etc..). Not putting brackets around ```type``` works, though.

## Example from above link
```html
<alert *ngFor="let alert of alerts;let i = index" [type]="alert.type" dismissible="true" (close)="closeAlert(i)">
  {{ alert?.msg }}
</alert>
```
### Bugged Example
```html
<alert [type]="success" dismissible="true" *ngIf="this.successMessage">{{successMessage}}</alert>
```
### Screenshot
![image](https://cloud.githubusercontent.com/assets/2928421/20563432/9e2e5f7a-b156-11e6-92bc-8848794f30c5.png)

## Working example
```html
<alert type="success" dismissible="true" *ngIf="this.successMessage">{{successMessage}}</alert>
```
### Screenshot
![image](https://cloud.githubusercontent.com/assets/2928421/20563589/42a4a686-b157-11e6-8d70-850aee28b06e.png)

**Comment by valorkin** [comment]
`<alert [type]="success"` will not work if `success` is not an property on component
`[]` will evaluate `success` property value and it is `undefined`
`type="success"` treats `success` as string literal and it works fine

BTW I don't see `<alert [type]="success" dismissible="true" *ngIf="this.successMessage">{{successMessage}}</alert>` on demo page

Please close an issue if I answered your question ;)

**Comment by wrkhenddher** [comment]
We are experiencing a somehow related issue:

We're binding `<alert>` `[type]` but when our backing object `type` property changes (on the TypeScript side), the `<alert>` element doesn't change correctly.

Here is a rudimentary example:

```html
<div>

{{myBackingObject.type}} {{myBackingObject.message}}

<alert [type]="myBackingObject.type">{{myBackingObject.message}}</alert>
</div>
```

```typescript

myBackingObject = { "type" : "info" };

ngOnInit() {
this.myBackingObject.type = 'info';

setTimeout(() => this.myBackingObject.type = 'success', 3000);
}
```

I guess it's because the `<alert [type]='myBackingObject.type'>` is not propagating the value of `type` to its inner `<div class="alert alert-<type>">` ???

Here are 2 screen shots taken with Chrome dev tools

The first one shows the `<div>` containing plain text interpolated from our backing object and the `<alert>`.

The second screen shots shows the `DOM` structure after changing the value of type in our backing object. See that the `<alert>` shows `ng-reflect-type="success"` but the inner `<div class="alert alert-info">` instead of `alert-success`.

![image](https://cloud.githubusercontent.com/assets/5215870/20846035/5a2912fa-b88d-11e6-976b-7b7bc48794bd.png)

![image](https://cloud.githubusercontent.com/assets/5215870/20846041/5e9653f2-b88d-11e6-90ce-968768701ed9.png)

Any help is appreciated

**Comment by valorkin** [comment]
@woodrufs ok, it is a nice reason for small PR to documentation ;)

**Comment by valorkin** [comment]
fixed, check docs preview http://valorkin.github.io/ng2-bootstrap/#/alerts

**Comment by woodrufs** [comment]
@wjehenddher - I am having this issue as well. I had to work around it by using the standard Bootstrap 4 classes and then binding to [ngClass].
```
<div *ngIf="alert && alert.type && alert.message" class="form-group row">
      <div class="col-md-6 offset-md-3 alert" [ngClass]="{'alert-success': alert.type === 'success', 'alert-danger': alert.type === 'danger', 'alert-info': alert.type === 'info', 'alert-warning': alert.type === 'warning'}">
        <a *ngIf="onAlertClose.subscribed"(click)="onAlertClose.emit(formGroup)" name="close" class="close">&times;</a>
        {{alert.message}}
      </div>
</div>
```

**Comment by mateenQureshi** [comment]
@valorkin i m getting this warning:

```
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///path/to/Projects/Angular-cli-tests/test-three/node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlertComponent.html@1:0
```

help me removing this warning message.. it comes when i use to build my project, in dev mode, it works fine
Thank you!

**Comment by valorkin** [comment]
@mateenQureshi use v2 of ngx-bootstrap, or don't pay attention to it

**Comment by mateenQureshi** [comment]
@valorkin  yeah, i just check the v2 and warning is gone now.

Thanks!
