### ISSUE TITLE
There is no directive with "exportAs" set to "bs-modal"

### ISSUE THREAD

**Issue by albertoramires** [valor-software/ngx-bootstrap#1276]

**Comment by valorkin** [comment]
try replace 
`import { Ng2BootstrapModule } from "ng2-bootstrap/components";`
with 
`import { Ng2BootstrapModule } from "ng2-bootstrap/ng2-bootstrap";`
if not there are was similar issues https://github.com/valor-software/ng2-bootstrap/issues?q=is%3Aissue+bs-modal+is%3Aclosed

**Comment by albertosramires** [comment]
Thanks @valorkin, but that didn't fix the issue. I've went through all the issues regarding this same problem and most of them seem to have been fixed with importing Ng2BootstrapModule or ModalModule in the correct place. I don't know where else I could import it since this is the only module on my app. 😞

**Comment by albertosramires** [comment]
Fixed, issue wasn't with ng2-bootstrap, it was with the haml loader, thanks again.

**Comment by valorkin** [comment]
Can you please describe it here, just in case some one will face it?

**Comment by albertosramires** [comment]
I was using [haml-haml-loader](https://www.npmjs.com/package/haml-haml-loader) to load haml into my webpack ng2 app but there seems to be some issue with that loader and directives so they were being omitted which caused errors with a lot of ng2-bootstrap's directives.

**Comment by valorkin** [comment]
Thanks!
