### ISSUE TITLE
rename project as ng2 no longer viable

### ISSUE THREAD

**Issue by born2net** [valor-software/ngx-bootstrap#1355]
rename project as ng2 no longer viable
I know ```ng-bootstrap``` is taken, so maybe ```angular-bootstrap```
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by pkozlowski-opensource** [comment]
Or better yet join ng-bootstrap efforts as having 2 libraries that are solving the same problem is sub-optimal from the community point of view.... I've already extended the offer to @valorkin as I think that there are enough problems to solve in one library (rock solid animations, accessibility, keyboard support etc.).

IMO it makes sense since this library:
* needs to change the name as pointed out by @born2net 
* needs to change APIs (lack of prefixes) 

Anyway, just stoping by to say that we (ng-bootstrap) folks are a friendly bunch and open to collaborate with anyone who aims at creating a set of quality widgets for Angular based on Bootstrap.

**Comment by valorkin** [comment]
Will be renamed, in ngx maybe.
We will merge one day :)
