### ISSUE TITLE
Typeahead show more than typeaheadOptionField in the visible input field

### ISSUE THREAD

**Issue by jtweeks** [valor-software/ngx-bootstrap#1434]
The input field a user clicks on to filter the drop down displays the users selection but currently only displays the typeaheadOptionField.  It would be nice to be able to also display other object properties, like the template allows in the filtered list

**Comment by jtweeks** [comment]
Example, for a country I have an array of objects with "name" and "code"  I want the typeahead to filter the list by searching both, and I want the display in the input field to display both, but I wan't the value in the model to only be the "code"

**Comment by critchie** [comment]
Since you have a complex object you have moved beyond the simplest use case of the typeahead.  For filtering on both fields you should provide the typeahead an Observable like in the asyncSelected example.

For the other parts what I do in this situation is to provide a field that concatenates the values I want to display in the option field.  This doesn't solve the second part of having just the "code" in the selected value but I think the design is such that you attach a handler to the typeaheadOnSelect event where you get the entire object back in the event.item property when an item is selected.  In this case it would be event.item.code.

But it would be pretty slick if there was an option template.  The problem is I don't think this optionTemplate could do anything but return a simple string (no HTML for example).  I think what most typeaheads do is allow you to provide an optionFormatter function that accepts the selected object and returns a string to display.  And as I carefully read the documentation it looks like something similar is already available (that I personally just glossed over several times until now).

The documentation states that the typeaheadOptionField "Supports nested properties and methods.".  This makes it sound like if the value of the typeaheadOptionField is a method it will call that method to get the option string.

optionFormatter or method on an object...  pluses and minuses to both approaches.

**Comment by jtweeks** [comment]
@critchie I went the method way and catching the result in the select method to then store the code
thanks
