### ISSUE TITLE
Popover-custom position arrow

### ISSUE THREAD

**Issue by sergeushenecz** [valor-software/ngx-bootstrap#1653]
Can I change position arrow popover? I have seen it calculated position dynamic on the center blocks

Can I do  so?
![image](https://cloud.githubusercontent.com/assets/7217517/23015494/1599590e-f444-11e6-94f2-c3ff2f4157bc.png)

**Comment by valorkin** [comment]
you can use `placement` param to change arrow position
http://valor-software.com/ng2-bootstrap/#/popover#popover-directive

but if you meat something like: popover on top but arrow at right,
than no, at least at the moment
it could be available later when I will rewrite positioning service

**Comment by jainanuj0812** [comment]
@valorkin Any update on this?

**Comment by 1-0-1** [comment]
This would be very helpful for me.  I have wide popovers being used in a grid and would like to have the popover more or less centered in the grid rather than over the cell and have the arrow point to the source cell.
Perhaps a way to over-ride the tendency to change the width/height of the popover/tooltip and instead shift the positioning.  This would be a helpful option to have when popovers/tooltips are close to an edge.

**Comment by shanieMoonlight** [comment]
@1-0-1  You can try something like this:
<div class="ml-3" [popover]="oneLineTemplate" [popoverTitle]="_heading" [isOpen]="isPopoverOpen" style="width:10px"></div>
<div   (mouseenter)="isPopoverOpen=true" (mouseleave)="isPopoverOpen=false">
Actual content goes here
</div>

The top div is an empty div that takes up no space but the pop-over will be attached to it. You can put it anywhere you like and the popover will follow it.
