### ISSUE TITLE
Bootstrap 4 datepicker - months and years are not nice

### ISSUE THREAD

**Issue by kuba007** [valor-software/ngx-bootstrap#1871]
It can be seen here: 
http://valor-software.com/ngx-bootstrap/index-bs4.html#/datepicker

When swiched to month mode or year mode, arrows and buttons look different (bs3 way, I believe).

![image](https://cloud.githubusercontent.com/assets/9961108/24711120/542962f8-1a1f-11e7-9ac0-6adc58d0af4a.png)

**Comment by maxailloud** [comment]
Have you activated the Boostrap 4 theme mode like explained [here](https://github.com/valor-software/ngx-bootstrap/blob/development/docs/getting-started/bootstrap4.md#let-ngx-bootstrap-know-you-are-using-bs4) ?

Can be the reason why.

**Comment by kuba007** [comment]
Yes, I did. Day picking part is ok, but in months and years is used btn-default, instead of btn-secondary. It can be demonstated in the official demo as well - http://valor-software.com/ngx-bootstrap/index-bs4.html#/datepicker

**Comment by wmarques** [comment]
In my app the datepicker doesn't change when i switch between month, year and day, but I lost "chevron" in month and year datepickers. 
@valorkin 
I think it's because you don't do `[innerHTML]="CURRENT_THEME_TEMPLATE.ARROW_LEFT"` inside month and year components, so it's looking for "glyphicons" which are not included in BS4.

Do you want me to do a PR for this ?

**Comment by kuba007** [comment]
Yes!

**Comment by valorkin** [comment]
this PR was merged and published

**Comment by valorkin** [comment]
thanks again :)

**Comment by kuba007** [comment]
I still see the buggy behavior in ngx-bootstrap v1.9.1. What is the fix version?
