### ISSUE TITLE
Navigate to tab.

### ISSUE THREAD

**Issue by chris93007** [valor-software/ngx-bootstrap#1975]
Is it possible to switch tabs while clicking on some other element on the page?

**Comment by kvanbere** [comment]
Trying to do this ... finding it hard to believe it's not possible. Nothing I've tried has worked. For example:
```
@ViewChild('tabGeneral') tabGeneral: TabDirective;
```
then
```
tabGeneral.active = true;
```
.. doesn't work, and there's no hints in the docs. I've also tried looping through the tabs of the tabset, but no `id` is exposed on each tab.

**Comment by kvanbere** [comment]
... OK so I found a workaround. My tabs were static so I was able to do something like this:
```
@ViewChild('tabSet') tabset: TabsetComponent;
```
```
    this.route.queryParams.subscribe(params => {
      let tab = ["general", "flights", "invoices"].indexOf(params['view']);
      this.tabset.tabs[tab > -1 ? tab : 0].active = true;
    });
```
Mark the tabset with `#tabSet` in the html.
```
<tabset #tabSet>
```
This will respond to routes like `?view=flights` or `?view=bookings` .. need to update the order of the array each time you add/remove a tab since there's no way to select the tabs based on their id, I think?

You could do a similar thing if you were pressing a button and wanted to swap to each, *as long as they are in a static order*.

**Comment by IlyaSurmay** [comment]
Use `@ViewChild('tab') tab: TabDirective` for static tabs and then manipulate its `active` property;
For dynamic tabs - manipulate `active` property of tab object.

**Comment by kvanbere** [comment]
For dynamic tabs you can't tell which tab is which because it doesn't even expose an id.
