### ISSUE TITLE
combine bootstraps?

### ISSUE THREAD

**Issue by PatrickJS** [valor-software/ngx-bootstrap#2]
@mlaval has a Carousel and @SebastianM also made a progressbar

how can we combine all efforts? Or is it a race to the first one who finishes the conversion

**Comment by sebholstein** [comment]
@gdi2290 good point. Didn't know about the other projects.

IMO it's totally useless that there are 3 angular2-bootstrap projects. I would suggest that we combine our efforts in one Github organization. What do you think? @mlaval @valorkin

**Comment by marclaval** [comment]
It's not a race :) Mine is still more a sand box project to experiment with Angular 2 as an external user, trying to explore all aspects of the dev experience. I'm using the Bootstrap carousel because I've done the same with several frameworks in the past, so it's a nice way to compare them.

IMO, it's a bit too soon to start a such a serious project, I would probably wait for the beta. But once it is there, I would definitively expect to have one common project, for example in https://github.com/angular-ui

**Comment by valorkin** [comment]
+1 to combining
my goal is to produce 1 to 1 API and behavior (as much as possible) with ui-bootstrap and 
cover it with migration guide per component
- popover is just a superset of tooltip
- Carousel\Modal\Datepicker - is another beast

currently reading new router code, to see best practice in writing bind-html

**Comment by valorkin** [comment]
Carousel\Modal\Datepicker on the way

**Comment by sebholstein** [comment]
:+1: 
@valorkin What do you think of the idea to create a seperate organization and merge our two projects?

**Comment by valorkin** [comment]
@SebastianM it is already in organization I would love to stick for now

**Comment by valorkin** [comment]
@SebastianM what about name of this project `ng2-bootstrap` or rename it to `angular2-bootstrap`?

**Comment by valorkin** [comment]
Added demos with bootstrap 4, now module can be used as npm module, added ng2-bootstrap started repo
This week I am expecting to have 95% of baseline functionality implemented, so there are no sense to merge, closing this issue

**Comment by briantopping** [comment]
Also note https://github.com/ludohenin/angular2-seed-ng2-bootstrap which is the very powerful TS-driven build of https://github.com/mgechev/angular2-seed with ng-bootstrap added in.

**Comment by valorkin** [comment]
@briantopping works good now with angular2-seed now, I will add to read me

**Comment by briantopping** [comment]
Thanks @valorkin. I tried using the accordion in my project but the application crashes with a weird error when I even have the accordion component referenced. See https://github.com/briantopping/angular2-seed/blob/1266b01f36d3d0e9d6857e6663ac910bbf5312ef/app/components/navigation/navigation.ts#L38-L68. Should that work okay?

**Comment by valorkin** [comment]
ok, I will try to check in nearest time

**Comment by briantopping** [comment]
ok thank you! :)

**Comment by briantopping** [comment]
Hi @valorkin, just wanted to let you know I resolved the problem and leave some potential feedback. The issue was the import on the library was different and I wasn't knowledgable enough yet to recognize the difference. This caused the library load URI to be incorrect. 

I'm curious if this was avoidable. Do you have any feedback on the manner that this project is using imports and could it be improved or is it something that might be better and you want to bring back in to ng2-bootstrap? I don't have enough experience to critique at all, just curious if something could be improved after the experience.  Cheers!

**Comment by valorkin** [comment]
Hey, always look for a ways to improve lib, first thing I see 
Replace import from 'ng2-bootstrap' to import from 'ng2-bootstrap/ng2-bootstrap'

**Comment by briantopping** [comment]
Haha, well I don't really know what I am doing with Javascript, so I don't know which is better. :)

**Comment by valorkin** [comment]
It is not so about javascript, it is more about typescript modules, they are pretty fresh
so basically, like with angular2\angular2 I had to import ng2-bootstrap\ng2-bootstrap

**Comment by linusbrolin** [comment]
Sorry for commenting on a closed issue, but there are still two separate ng2-bootstrap projects so I thought I'd ask about it.
Are you aware of the ng2-bootstrap project from the ui-bootstrap team?
[https://github.com/ng-bootstrap/core](https://github.com/ng-bootstrap/core)
It seems like such a waste of effort to have two separate projects with the same goal, instead of combining them.

**Comment by valorkin** [comment]
@linusbrolin yeap, when I started this project I have proposed a cooperation to ui-team
somewhere around of 1 August 2015 (this repo started a week later)
in short they said `no`,
and started mentioned repo at Sep 15
But I am totally agreed, that duplication is waste of efforts,
but sometimes it can give a nice result

**Comment by linusbrolin** [comment]
Alright, thanks for the info.

Btw, I've made a different Accordion component, that behaves more like the Bootstrap3 one (with a button effect). I call it BtnAccordion.
It uses the Collapse component from this repository, but with added animations and I use FontAwesome for the up/down glyph icons, since Bootstrap v4 does not include those fonts anymore.
Are you interested in it?
What would be the best way for me to upload it in that case?
Fork the project and then do a PR with my additions?

**Comment by valorkin** [comment]
@linusbrolin I will appreciate 
separate PRs for
- collapse with animation
- compare accordion

Of course I am interested :)
