### ISSUE TITLE
Support for Navbars

### ISSUE THREAD

**Issue by abhishekchandran** [valor-software/ngx-bootstrap#2061]
div id and data-target doesn't seem to work

 https://v4-alpha.getbootstrap.com/components/navbar/#external-content.

**Comment by valorkin** [comment]
nice one thanks

**Comment by IlyaSurmay** [comment]
It's strongly recommended to avoid all interactions with DOM in Angular, that's why `data-target` doesn't work. Typical scenario for collapse module is shown [here](https://valor-software.com/ngx-bootstrap/#/collapse#basic) - you add `[collapse]="bool"` to a target and then manipulate `bool` var from outside (button, event etc)

**Comment by valorkin** [comment]
@IlyaSurmay I didn't tell yet, but I will add services to work with data attributes,
performance wise it's great, especially for tables :)
don't share this yet
