### ISSUE TITLE
Tooltip doesn't load for elements made by ngFor function

### ISSUE THREAD

**Issue by MPVogelPaint** [valor-software/ngx-bootstrap#2379]
If you use `*ngFor="let item of items"` on an array, you can then use the tool tip with each item it creates.
If you use `*ngFor="let item of function(items)"` where function returns an array to loop over then the tool tip isn't able to be added to those items.

Here is a plunker to demo it:
https://plnkr.co/edit/B6YyJAoabfMSwANZgZAW?p=preview

**Comment by IlyaSurmay** [comment]
Hi. Actually, it works :) The issue here is in the nature of Angular's change detection.
If you're using function as a source of items in ngFor, this function is called every time when Angular is performing change detection. And checking is done every time when any event is dispatched - click, hover, mousemove, etc. So basically you just can't manage to see a tooltip because every time you hover on a tooltip container, Angular is doing change detection, which means that the whole DOM tree of ngFor is replaced, and table rows have been re-rendered with the data which was returned by function, and original container of tooltip is no longer exists. 
If you take a look you'll see that it's also not possible to select any part of text for the same reason - DOM tree is being replaced over and over when you're moving a cursor over ngFor content.

I see two possible options here:
1. Get rid of using a function in ngFor;
2. Use ChangeDetectionStrategy.OnPush in your component. This will reduce a number of checks and Angular won't be replacing the DOM tree of table every time when a UI event is dispatched

I've created a simple example where you'll see the difference between default change detection strategy and OnPush
https://plnkr.co/edit/EcZry3zunfOs80dbuPrh?p=preview
