### ISSUE TITLE
ModalService callback called many times.

### ISSUE THREAD

**Issue by riteshnus** [valor-software/ngx-bootstrap#2613]
I want to open a modal from a component which has some webservice call.  So I used the below code to open a modal. As you see in code modal is opened in a different component.  From that component, i had some web service call. once call got over I used modal service service to refresh the parent page with the updated list. 

To refresh the page I am using modal service onhide callback to refresh the parent list. For the first time it works as usual but it run twice/trice it run the onhide callback function multiple times. 

open a modal: 
this.bsModalRef = this.modalService.show(CreateProgramComponent, constant.config);

callback onhide:
this.modalService.onHide.subscribe(() => {
     this.programs.push(this.programService.getProgramData());
   });

I suspect that the modalservice is not destroy/close on every hide. It keeps continuing that's why callback calls run multiple time.

**Comment by IlyaSurmay** [comment]
Could you provide an example in plunkr or repo? Because it works fine for me.
Here is the demo https://plnkr.co/edit/hLacTPzEpH4nn5tKHD2g?p=preview which shows how many times events are called.

**Comment by s00pa** [comment]
I might be completely offtrack but I've seen a similar issue where if the template contains an angular component, the component seems to never get destroyed and results in strange side effects if it contains inputs. I'm not sure if modals are meant to support nested angular components though. 

I modified your plunkr to demonstrate the issue I'm having. If it's not the same as the original post then I apologize and perhaps it should be filed separately. In the plunkr I added a Test Component and within that I have a getter and setter that adjusts a BehaviorSubject through an input. This is really to demonstrate the big issue with the component not being destroyed because each time it is created, all of the previous behavior subjects trigger. You'll need to open the console log to see what I'm getting at. I would have thought on hiding the modal, it would destroy the components within it

[https://plnkr.co/edit/9EvFkwXAB4MTuKsjgcZj?p=preview](https://plnkr.co/edit/9EvFkwXAB4MTuKsjgcZj?p=preview)

Thanks

**Comment by s00pa** [comment]
I figured my issue is probably different to the original poster's issue so I've filed it separately
[Issue 2675](https://github.com/valor-software/ngx-bootstrap/issues/2675)

**Comment by IlyaSurmay** [comment]
Closed for inactivity. Will be reopened if you provide a plunkr/stackblitz with reproduction

**Comment by wkjesus** [comment]
Are this issu solve i have the same result, when create a modal with componente and subscrube to feedback when hide the modal. the subscriptions evokes "n" times more when initially.

**Comment by samsop** [comment]
gud answur

**Comment by rafael-andrade** [comment]
Having same problem, what did you guys do ?

**Comment by krlozadan** [comment]
Hello, I have the same problem here. Have some come up with a solution?

**Comment by narayanabojja** [comment]
Hello everyone,
I had same issue. I got it resolved by implementing solution from below link. 

https://stackoverflow.com/questions/50361938/angular-5-bootstrap-dialog-submitting-requests-multiple-times?rq=1

I am sharing the above link which may be helpful for other people.
Happy Coding !!
