### ISSUE TITLE
entryComponents do not use module's shared providers for injected services

### ISSUE THREAD

**Issue by ilovett** [valor-software/ngx-bootstrap#2634]
When instantiating a new modal useing `bsModalService.show(MyEntryComponentModalWhichUsesMySharedService)`, when instantiating the `MyEntryComponentModalWhichUsesMySharedService`, a brand new instance of `MySharedService` is instantiated, disconnected intended shared services.

EG:

```
@NgModule({
  imports: [
    ...
  ],
  declarations: [
    ComponentWhichUsesMySharedServiceA,
    ComponentWhichUsesMySharedServiceB,
    ComponentWhichUsesMySharedServiceC
  ],
  exports: [],
  providers: [
    MySharedService
  ],
  entryComponents: [
    MyEntryComponentModalWhichUsesMySharedService
  ]
})
```

In this case, all the declared components which all share the same instance of injected `MySharedService`, but when the `MyEntryComponentModalWhichUsesMySharedService` modal is created, a brand new instance of `MySharedService` is created.  I would expect the same instance to be passed.

**Comment by IlyaSurmay** [comment]
Hi, could you reproduce this issue in plunkr/stackblitz? 
You can use one of starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by ilovett** [comment]
Went to reproduce this and did not have the issue so closing.

**Comment by ebi-igweze** [comment]
Hey.. I had the same issue, after I saw this posted issue, I wondered why you couldn't reproduce it, I eventually figured out what caused mine, maybe it's what caused yours as well.
I had two ngModules 'SharedModule' - SM and 'HomeModule' - HM, now the entry components were marked in 'SM' but were being dynamically loaded by component in HM, and both modules had the Service marked as a provider in them. So the component in SM wasn't instantiated with the service in HM, hence whatever changes the component made in HM, the component in SM was not updated, due to different insatances, as you mentioned.

Solution: I moved the Service to be a provider in the common ngModule having both the SM and HM; in my case the root AppModule, and now both components are pointing to the same insatnace. everything works well.
