### ISSUE TITLE
Failed to load bs-datepicker-view.html

### ISSUE THREAD

**Issue by pgeyman** [valor-software/ngx-bootstrap#2678]
Hi,
Is there specific additional config to use the Bsdatepicker as I get this error:
Failed to load bs-datepicker-view.html

I'm using npm and webpack 1

**Comment by valorkin** [comment]
Please upgrade to webpack 2, and make sure you are installing from npm.
If use persists, please post here package.json and webpack config

**Comment by srmico** [comment]
Hello,
I am having the same issue, but i'm using systemjs.
I believe the issue could be the use of templateUrl in the file ngx-bootstrap.umd.js line 11875, but I could be wrong

**Comment by pgeyman** [comment]
Upgrading to webpack 2 (well actually webpack 3) fixed the issue for me. :triumph:

(I just need to resolve all the other issues that has given me now  :grimacing: ...luckily it was on my development roadmap anyway :relieved: )

**Comment by fiedi** [comment]
As @srmico I'm using systemjs :( if You find any solution, please, send it

**Comment by valorkin** [comment]
@fiedi I can confirm an issue with UMD bundle, I need to update configuration of it

**Comment by mkzrt** [comment]
The same issue continuing for me but I don' use webpack. This problem is stated as " 404 GET /bs-datepicker-view.html".  My project usage as: 

[import { BsDatepickerModule } from 'ngx-bootstrap';

@NgModule({
  imports: [BsDatepickerModule.forRoot(),...]
})
export class AppModule(){}
]

**systemjs.config.js**

[map: 
{
"ngx-bootstrap":"node_modules/ngx-bootstrap"
}

packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            },
            'angular-in-memory-web-api': {
                main: './index.js',
                defaultExtension: 'js'
            },
            'ngx-bootstrap': { format: 'cjs', main: 'bundles/ngx-bootstrap.umd.js', defaultExtension: 'js' },
            'moment': { main: 'moment.js', defaultExtension: 'js' },
        }
](url)

**Comment by gabosvk** [comment]
Please, is there any update for systemjs? I'm having the same issue and I really need to solve it... Thanks.

**Comment by gabosvk** [comment]
ok I found a temp fix here https://stackoverflow.com/a/46419973/3073950 but def. a fix from valor-software would be appreciated...

**Comment by valorkin** [comment]
Actually, I did the fix, need to test and publish it as beta.6

**Comment by rudhras** [comment]
@valorkin - is the fix published yet? please mention when this is available.

**Comment by valorkin** [comment]
npm i ngx-bootstrap@next

**Comment by alexzatarain** [comment]
im still getting this error , even with the workaround , 
 Failed to load node_modules/ngx-bootstrap/datepicker/themes/bs/bs-datepicker-view.html and i am seeing the html on the node_modules folder  :( any tips ?

the ngx-bootstrap@next works with angular 2.4? because i tried and is using some export named renderer2 in angular/core  , and is not recognized in my project.@valorkin

**Comment by valorkin** [comment]
@alexzatarain nope, @next doesn't work with ng v2, now it works with v4 and v5
I had to drop it at some point, sorry
