### ISSUE TITLE
BsDatePicker has z-index issues with bootstrap input-group

### ISSUE THREAD

**Issue by chubbard** [valor-software/ngx-bootstrap#2707]
This is easy to reproduce because it happens on the demo page in the theme example.  If you open up developer tools and toggle to mobile device toolbar.  Then click the Open button in the theme switching example and you'll see the problem.  The `bs-datepicker-container` is underneath the text field.  The reason is that `.input-group .form-control` in bootstrap have their `z-index`'s marked to 2.  Putting a `z-index` on the container of 5 fixes it.

**Comment by leomayer** [comment]
Yeah, but doesn't fix the issue if the datepicker runs in another environment where the z-Index is higher (e.g. modal dialog). 
Plus I wanna mention that if you have a wrapper around the component and place the `css` in an separate file, eg.  

```
@Component({
...
styleUrls: ['datepicker.css'],
encapsulation: ViewEncapsulation.None,

```

than you have to use `ViewEncapsulation.None,` otherwise the `css` is ignored. The reason why I mention this here is that setting the `z-index` for `.bs-datepicker {` to 5 works well until you resize your frame. Than all of sudden the `z-index` is reset to 1 although the `css` has a set of 5!

So guess there are several side effects with the `z-index` and the current setup...

**Comment by chubbard** [comment]
Given that this is a library used in conjunction with bootstrap AND since it's on the demo page I wouldn't try and over think this one.  You know anyone using this library will have bootstrap included in the CSS so you may as well work around this issue and fix it.  

Sure people can always add more CSS to the page that can be in conflict with the styles here, but that's just CSS.  It's maddening to fix it, but CSS would need to fundamentally change to address some of the issues you raise.

**Comment by NenadJovicic** [comment]
put this in your styles.css and nothing will go over datepicker
`bs-datepicker-container {
  z-index: 9999 !important;
}`

**Comment by chubbard** [comment]
I'm trying to help you identify what would be better experience out of the box.  I know I can set the zindex as I've already fixed it in my environment.  This is a bug in the current solution that I think should be fixed.  Especially since the new BsDatePicker is still under development I thought it important to send bug reports on where it's not working well.

**Comment by valorkin** [comment]
@chubbard you are correct, it was fixed and published in beta.5 (@next) version

**Comment by valorkin** [comment]
@chubbard next issue with z-index is modals (

**Comment by anmol-rodi** [comment]
@NenadJovicic  Thanks mate it worked for me !
