### ISSUE TITLE
[WARNING ->]<template></template>

### ISSUE THREAD

**Issue by kainonly** [valor-software/ngx-bootstrap#2916]
[WARNING ->]<template [ngIf]="!isClosed"><div [class]="'alert alert-' + type" role="alert" [ngClass]="classes"") ng:///node_modules/ngx-bootstrap/alert/alert.component

Hope to update the warning in NPM

**Comment by IlyaSurmay** [comment]
Please search for same issues before opening a new one... https://github.com/valor-software/ngx-bootstrap/issues?utf8=%E2%9C%93&q=alert%20template

For Angular 4 just use the @next version which fixes this warning. This cannot be fixed in 1.X.X because it would break Angular 2 support. You can use npm install ngx-bootstrap@next
