### ISSUE TITLE
How to change {{ Form.value }} from Datepicker with reactive forms

### ISSUE THREAD

**Issue by davidrdz93** [valor-software/ngx-bootstrap#2934]
I am working with this example: 
https://valor-software.com/ngx-bootstrap/#/datepicker#reactive

As you see the value of {{ Form.value  }} for 'date' is in the format "date": "2017-10-14T17:38:53.000Z", How it is posible to change that to "14/10/2017" as example, because that format is not passing my 
 regex validation! 

I have tried playing around with the code example and I also read all the documentation about DatePicker Module but I wasn't able to figured out how to do it!

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3

Angular: 4.2.4

Bootstrap: 3.3.7

**Comment by IlyaSurmay** [comment]
Value is always a Date object. You can parse and format it as you need to, for example you can format it with `.toLocaleDateString()` method of Date object.

**Comment by davidrdz93** [comment]
@IlyaSurmay just last thing! Where should I format that property ? In my component ? Can you please give a few lines of code with an example? Thank you!

**Comment by IlyaSurmay** [comment]
It depends on your task, you can format it right after ngModel is changed or before submitting the form.

**Comment by davidrdz93** [comment]
However there is something that is not going right, If you see the example again, if you type any value into the input tag with has bsDatepicker directive {{ Form.value }} is not being updated...

**Comment by valorkin** [comment]
When you do {{ form.value }} use date formatted pipe, https://angular.io/api/common/DatePipe
Post formatting user input is known request, working on it

**Comment by gavinsui** [comment]
hi,guys,can u solve this problem ?
i need your help ~~

**Comment by exsoflowe** [comment]
Any solutions (for custom format inside reactive forms) from here or SO don't work for me.
For example, it's uncomfortable to use setValue inside datepicker component wrapper. In this case you can't use parallel form control valueChanges subscriber, because it will return unformatted date. And you need to subscribe on parent of FormControl.

So I created component with input (using ngModel) which implements ControlValueAccessor interface
[stackblitz](https://stackblitz.com/edit/angular-ngx-datepicker-reactive-form-custom-format)

If you will use this component inside another wrapper and pass form group via @Input(), you can get ExpressionChangedAfterItHasBeenCheckedError.
In this case you can try to use `this.changeDetectorRef.detectChanges();` (see app.component.ts)
