### ISSUE TITLE
typeahead with typeaheadMinLength=0  is automatically selecting a value on Tab

### ISSUE THREAD

**Issue by avril-verhaeghen** [valor-software/ngx-bootstrap#3106]
I have a form with multiple input fields. When I'm adding some data in one field and then use the tab key to a typeahead field it automatically selects the first value from the array. This is not the case if I use a click event. Is this normal behaviour?

```
<input id="street" class="form-control" [formControlName]="'street'" tabindex="3"
                               [typeahead]="data.streets" [typeaheadMinLength]="0"
                               [typeaheadOptionField]="'name'" [typeaheadScrollable]="true" autocomplete="off">
```

Any suggestions?

Thanks!

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular: 4.4.6

Bootstrap: 3.3.7
Ngx-bootstrap: 2.0.0-beta.8

### Build system: Angular CLI, System.js, webpack, starter seed:
angular-cli: 1.3.2
node: 6.11.3
npm: 3.10.10

**Comment by avril-verhaeghen** [comment]
Found it. had my input field with the [typeaheadMinLength]="0", as shown in the docs this show the entire list on focus. 

I think this is a bug because when you use the tabular key it doesn't show the list, it just selects the first one in the list.

**Comment by 7185** [comment]
You're right. I can reproduce it.
Actually it shows the list for me but it disappears as soon as I release the tab key.
This is what is happening : 

1. You're typing in your first input (classic)
2. You press the tab key (keydown)
3. The focus moves to the second input (typeahead)
4. The entire list is shown with the first element highlighted
5. You release the tab key (keyup)
6. The focused element is added because of https://github.com/valor-software/ngx-bootstrap/blob/development/src/typeahead/typeahead.directive.ts#L223

I managed to prevent it by pressing and releasing the tab key very quickly, but that's probably because my list comes from an http request and it makes it slow enough. On the other hand, if I keep the tab key pressed, I can select the item that I want because the list stay visible.

My guess is that checking for the keyup event on the tab key is a bad idea in this situation.

**Comment by davidsekar** [comment]
This issue affects keyboard accessibility.
+1 for a fix.

**Comment by 1-0-1** [comment]
Tab also doesn't fire typeaheadOnBlur so there is no way to reset the value of the input if they have typed in something and then tabbed out.
