### ISSUE TITLE
Datepicker and locales

### ISSUE THREAD

**Issue by Hesesses** [valor-software/ngx-bootstrap#3242]
I'm wondering why we need to specify locales on ngx-bootstrap like mentioned here:
https://valor-software.com/ngx-bootstrap/#/datepicker#locales

I'm using moment locales everywhere for dates and it just works.
`moment.locale(locale)`

Is it possible to use moment locales automatically?

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: beta-11

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular Cli

**Comment by IlyaSurmay** [comment]
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead
Datepicker doesn't depend on moment.js because we don't want to make our users pull extra 70kb (moment.js with locales), that's why we're using a custom implementation.

**Comment by Hesesses** [comment]
Thats a valid point. I still think that if you are already using momentjs you should be able to use those locales with the datepicker
