### ISSUE TITLE
docs(timepicker): Min-max demo example. When user once choose unavailable PM time, AM/PM button stops working

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3288]
### Bug description
- Go to Timepicker demo page
- Scroll to Min-Max example
- Enter time more then 5 hours and click AM/PM button for choosing this PM unavailable time
- Click on AM/PM button one more time

#### Expected result:
AM/PM button is working for available choosen time

![minmaxissue](https://user-images.githubusercontent.com/27342505/33992955-34811e8e-e0dd-11e7-923c-fcad987c74c0.gif)

## Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.11 and older versions

Angular: all supported

Bootstrap: 3rd and 4th

**Comment by Isirak98** [comment]
An added problem to this issue, is that you can manually edit the fields to invalid values and the picker will still accept them. 

Steps to recreate: 

1. Go to the Min - Max section of the Demo page
2. Use the spinners to navigate to the minimum value, 8:00 AM.
3. Type in 7 in the hour field, which results in the time being 7:00 AM The time picker accepts the value.

I do suspect the issue is the same with the minute section as well.

**Comment by ludmilanesvitiy** [comment]
Issue resolved: https://valor-software.com/ngx-bootstrap/#/timepicker#min-max
