### ISSUE TITLE
import component error

### ISSUE THREAD

**Issue by lanocturne** [valor-software/ngx-bootstrap#33]
Getting this error on my angular 2 seed project:
![image](https://cloud.githubusercontent.com/assets/4869206/11105022/2f656bbe-8881-11e5-8024-53a308d0ca91.png)

I have put reference on tsd.d.ts
`///<reference path="../../../node_modules/ng2-bootstrap/ng2-bootstrap.d.ts" />`

At my component file:
...
import {dropdown} from 'ng2-bootstrap';
@Component({
    ...
    directives: [..., dropdown]
})

I tried to import other components like accordion, also gets same error.

**Comment by ludohenin** [comment]
@lanocturne Your error has nothing to do with typings reference otherwise you'd get a compile time error. What you have is a runtime error.
From your log, it show that path for ng2-bootstrap isn't set correctly.
You should check those ones out:
- https://github.com/ludohenin/angular2-seed-ng2-bootstrap
- https://github.com/AngularShowcase/ng2-bootstrap-sbadmin

You can remove your comments `/// <ref.../>`.

**Comment by lanocturne** [comment]
Thank you @ludohenin . After checking your examples I found the issue is my seed project was not updated via ng2-bs and systemjs-builder configuration. HIGHLY recommend this reference https://github.com/AngularShowcase/ng2-bootstrap-sbadmin should be put on README.

**Comment by valorkin** [comment]
@ludohenin thank you for helping :)

**Comment by valorkin** [comment]
I tried to explain how to solve this issue here https://github.com/angular/angular.io/pull/681
