### ISSUE TITLE
ngx-bootstrap Datepicker - Add currant date in header

### ISSUE THREAD

**Issue by santoshshelke** [valor-software/ngx-bootstrap#3454]
How we can show current date in the header and on click of that user should be redirected to current date/month. Just like below image.

[
![capture](https://user-images.githubusercontent.com/2727301/34913593-bd8a7c68-f927-11e7-8bf1-b146331e37c8.JPG)
](url)

**Comment by IlyaSurmay** [comment]
There's no need to duplicate your question here since it's already been asked on StackOverflow https://stackoverflow.com/questions/48237801/ngx-bootstrap-datepicker-add-currant-date-in-header
Datepicker doesn't have such fucntionality. Looks like you're using old datepicker which isn't supported anymore. You can extend DatepickerComponent and add whatever you want.
