### ISSUE TITLE
ngx tabs (V2.0.0) remove icon (X) shows in red color.

### ISSUE THREAD

**Issue by shankar1414k** [valor-software/ngx-bootstrap#3559]
tabs with remove icon(X) shows as white in desktop , when I opened the same view in phone /ipad icon(X) shows in red 

Please advise

**Comment by IlyaSurmay** [comment]
There's no need to duplicate your question here since you've already asked it on Stackoverflow (https://stackoverflow.com/questions/48463498/ngx-tabs-v2-0-0-remove-icon-x-shows-in-red-color-in-phones-devices). For general questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead.

Remove icon has `bs-remove-tab` class that you can use to change icon color to whatever you like.

**Comment by shankar1414k** [comment]
even I tried with bs-remove-tab class.  it will only effect in desktop version, but in mobile it is shown as red.
Please advise

**Comment by IlyaSurmay** [comment]
Have you tried `!important`?

**Comment by shankar1414k** [comment]
this is how I try to override the remove (X) color:
.bs-remove-tab {
        color:blueviolet  !important;
}
it works on desktop version, but not working in mobile / devices
