### ISSUE TITLE
You can do better for modals

### ISSUE THREAD

**Issue by chaouiy** [valor-software/ngx-bootstrap#3567]
Sorry that I don't have any alternative to suggest but I can smell that every possible solution that `ngx-bootstrap` offer to deal with modals isn't as clean as it should be. We can do a lot better here to have cleaner/more maintainable/more angular friendly solutions.

**Comment by valorkin** [comment]
@amineparis no worries, modals is not that easy. Cuz they should be simple to use and easy to configure. Not saying it's dynamic injection part, which I had to rewrite 4 or 5 times since alfa 39 (~ first ngx-bootstrap release)

We know about it, and working on v2, stay tuned
There are a roadmap issue for modals ;)
