### ISSUE TITLE
Emitting a event whenever the data changes in dropdown

### ISSUE THREAD

**Issue by Varshamathukumalli** [valor-software/ngx-bootstrap#3675]
Hi,

I am using ngx-bootstrap to display dropdowns. I'm having children for each item in the drop down and i want to perform some operations whenever the data changes.
But unable to find any event related to this.
Kindly provide a way to solve this.

Regards,
Varsha

**Comment by IlyaSurmay** [comment]
Dropdown doesn't have such event because dropdowns are just containers for your data and they don't communicate with it at all.
If you want to be notified when the data in the dropdown changes, you need to use your own EventEmitter.
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead
