### ISSUE TITLE
How to initialize dropdownMenu when first load

### ISSUE THREAD

**Issue by justforuse** [valor-software/ngx-bootstrap#3682]
I find the dropdownMenu would not initialized until open the dropdown, But sometimes we may want to use the dropdownMenu data when first load.

**Comment by IlyaSurmay** [comment]
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

There's no direct way to achieve that because dropdowns are rendering just once on the first show. You can do a little trick though - show and hide the dropdown in `ngOnInit` if you're ok with that.
