### ISSUE TITLE
show only month in bsDatepicker 

### ISSUE THREAD

**Issue by suraj-karale** [valor-software/ngx-bootstrap#3707]
<input type="text" name="startDate" class="form-control" bsDatepicker [datepickerMode]="'year'" [minMode]="'month'" ngModel/>

#2627 this issue is not understandable. can you please help me in above code?

**Comment by IlyaSurmay** [comment]
This feature isn't yet implemented and there was a similar issue, so I closed your issue as a duplicate.

If you have questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead of creating a bunch of issues here.
