### ISSUE TITLE
Daterangepicker layout breaks in column with offset

### ISSUE THREAD

**Issue by dottodot** [valor-software/ngx-bootstrap#3749]
If you put the daterangepicker in a column with an offset (margin auto) to push it to the right the layout breaks (see screenshot attached).

But if I change the placement to 'left' it's ok as there is the space but it's not really where I want it.

```
<div class="row mb-3">
        <div class="col-md-auto px-1">
          <div class="btn-group">
        </div>
        <div class="col-md-auto ml-auto">
          <div class="input-group">
            <input class="form-control" type="text" name="daterangeInput" #drp="bsDaterangepicker" bsDaterangepicker placement='bottom'
              [(ngModel)]="bsRangeValue" (selected)="selectedDate($event)" />
            <span class="input-group-append" (click)="drp.toggle()">
              <span class="input-group-text">
                <i class="fa fa-calendar"></i>
              </span>
            </span>
          </div>
        </div>
      </div>
```

![screen shot 2018-02-12 at 09 38 57](https://user-images.githubusercontent.com/811652/36091162-bdfc77cc-0fda-11e8-9ce1-19f9982a9c95.png)

**Comment by IlyaSurmay** [comment]
Please provide a reproduction of this issue.
starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by pgeyman** [comment]
@IlyaSurmay See this plnkr: [url](https://plnkr.co/edit/nVuQVK1UllaVEXfhbe3J?p=preview])

Clicking on the date picker button, you will see the date picker style wraps. There is no option like the dropdowns to have it display from the bottom right edge rather than the bottom center. 
When displayed on the right of the screen there should be a style option that applies css position using "right: ..." rather than "left: ..."

There is currently no work around either, as there is no way to add a custom css class to the bs-daterangepicker-container element to override the element style left offset
