### ISSUE TITLE
[collapse] add option for custom css styles

### ISSUE THREAD

**Issue by fdu-axiometrics** [valor-software/ngx-bootstrap#376]
The added css styles (height, overflow) from collapse component breaks my own styles. 
And the collapse works fine without those two classes.

Is it possible to add another option for this? Or do we really need those two classes?

**Comment by davidbilge** [comment]
Should this not use bootstrap's [collapse](http://getbootstrap.com/javascript/#collapse) classes instead of directly setting `style`s anyways?

Edit: Instead of using `[collapse]="!whatever"` you can also say `[class.collapse]="!whatever"` which has pretty much the same effect for now. You only lose animation capabilities.
