### ISSUE TITLE
Bootstrap 4 & navbar menu (dropdown)

### ISSUE THREAD

**Issue by ctrl-brk** [valor-software/ngx-bootstrap#3760]
Trying to upgrade to Bootstrap v.4.

BsDropdown in navbar looks weird. What am I missing?

Here's the plunker. Notice the dropdowns alignment and the lack of 'pointer' cursor.
https://plnkr.co/edit/BnGLq0ypmSA82ZnnEUcD?p=preview

**Comment by IlyaSurmay** [comment]
`.nav-item` elements with dropdown have to have `dropdown` class, without it a dropdown won't be properly aligned. Also, if `<a>` doesn't have a `href` attribute, `cursor: pointer` isn't applied.

There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

**Comment by ctrl-brk** [comment]
Thanks. Using href doesn't make any sense. What kind of href? Just `href='#'`? I understand that this is not your issue but why? It redirects me back to the home page.

**Comment by IlyaSurmay** [comment]
I see three possible options here:
1. Use `href="javascript:void(0)"` instead of `href="#"`, this shouldn't redirect you to homepage.
2. Don't use `a` and replace them with `span` or `div`. This requires additional styling though.
3. Listen to a click event on a document and prevent default action if the click was done on `a` element with `href="#"` 
```
@HostListener('document:click', ['$event'])
  preventEmptyHrefNav(event: Event) {
    if (event && event.target && (event.target as Element).getAttribute('href') === '#') {
      event.preventDefault();
    }
  }
```

**Comment by ctrl-brk** [comment]
I just adjusted the cursor style.
Thank you for your help.
