### ISSUE TITLE
feat:typeahead Make selection on TAB optional

### ISSUE THREAD

**Issue by SidekickJohn** [valor-software/ngx-bootstrap#3842]
Hi Folks,

we are using ngx-bootstrap 1.9.3 and wanted to update to 2.0.2, but what keeps us from doing so, is the fact that Typeahead selects the highlighted Option on TAB-Button.

Our Feature-Request:
Would it be possible to change the "select on tab" that was handled in [Issue 3106](https://github.com/valor-software/ngx-bootstrap/issues/3106) to be optional?

Maybe add a new Input "disableSelectOnTab" of type boolean to the component and if its not set/false, the TAB Key triggers a selection (as it does now). If you would set "disableSelectOnTab" true then the Typeahead would behave like it did before and only select on "Enter"-Key.

What do you guys think of this?

**Comment by SidekickJohn** [comment]
Hi guys, I implemented a possible solution, that would suit our needs. Next up I'm going to file a pull-request an link to this issue.

**Comment by dwoodworth91** [comment]
Would really love to see this one completed.

**Comment by chubbard** [comment]
Yup this is killing my user base.  Please just add this.  What is the hold up here?

**Comment by ludmilanesvitiy** [comment]
This feature is already implemented and presented on the demo page:
https://valor-software.com/ngx-bootstrap/#/typeahead#selected-first-item

**Comment by ktschmincke** [comment]
It's useful to still allow selecting the first option via `Enter`, it's just `Tab` that poses a problem because `Tab` is used primarily to move through interactive elements on the page. People who can only use a keyboard are unable to move past a typeahead without selecting an option. But if the first option happens to be what they want, it would be helpful to allow that selection still.

The `typeaheadIsFirstItemActive` and `typeaheadSelectFirstItem` options seem to be an all-or-nothing approach to this issue but I feel like we need a little more nuance.
