### ISSUE TITLE
docs(dropdowns): add aria-attributes

### ISSUE THREAD

**Issue by tarusin** [valor-software/ngx-bootstrap#4097]
Need add aria-attributes to HTML code in `dropdowns` component.

- `role="button"` if tag not a button
- `aria-haspopup` indicates the button opens a menu
- `aria-expanded` shows whether the current item is expanded or collapsed
- `aria-labelledby` identifies the element (or elements) that labels the current element
- `aria-controls` indicates an element(s) whose content or behavior is controlled by the current item

Took as a basis - https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/menu-button/menu-button-links.html

**Comment by tarusin** [comment]
effort1: easy(hours)

**Comment by markayby** [comment]
The Lighthouse Accessibility verification does not pass for the button `aria-controls` attribute. It happens because before we click  the `dropdownToggle` button first time the element `<ul *dropdownMenu` does not present in the view. Thus `aria-controls` attribute contains the id of inexistent element.
