### ISSUE TITLE
How to localize old version datepicker ngx-bootstrap

### ISSUE THREAD

**Issue by liliom55** [valor-software/ngx-bootstrap#4279]
### feature request:

Thanks for new Datepicker but I have to work on old version of Datepicker and I'm not able to change the calender's view  to 'fr' (French) by old version of Datepicker. I saw some solutions here but non of them was practical for me. I've already use "moment" but it does not work and also there is not clear documentation for it.  If somebody could help to solve it I'll really appreciate. 

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: ^2.0.4

Angular:  ^5.2.0

Bootstrap: ^4.1.0

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI

**Comment by MichaelGamel** [comment]
use the following:
import { BsLocaleService  } from 'ngx-bootstrap/datepicker';
import { defineLocale } from 'ngx-bootstrap/chronos';
import { deLocale, daLocale, nlLocale } from 'ngx-bootstrap/locale';

defineLocale('de', deLocale);
defineLocale('da', daLocale);
defineLocale('nl', nlLocale);

export class AppComponent implements OnInit {

   constructor(private _localeService: BsLocaleService) { }
   ngOnInit() {
      this._localeService.use('de');
   }
}

for 'de' is a static value but instead of it you can retrieve the value from local storage, for example, to be based on user preference

**Comment by liliom55** [comment]
@MichaelGamel  
Thank you for your completed answer. but I think  it doesn't work for old version. I implemented your suggestion but the month's name and days' name have not been changed to French language

**Comment by valorkin** [comment]
Old datepicker will be added as theme to new one,
Heavy to change implementation of an old one was a reason for new datepicker.
You know, when rewrite is easier then fix :(

As a side note, you could try to add locale support for old datepicker
