### ISSUE TITLE
Wrong Date time json result when using Reactive forms

### ISSUE THREAD

**Issue by ahmadk** [valor-software/ngx-bootstrap#4285]
### Bug description:
Hi all
when I select date in a different month from the current real month I got a wrong json date result which is the selected date -1
By the way this bug shown event on your documentation page
https://valor-software.com/ngx-bootstrap/#/datepicker#reactive-forms
as I said in the title this bug seems to affects only the reactive forms 
Thanks in advance
### StackBlitz that reproduces the issue:
https://stackblitz.com/edit/ngx-bootstrap-tbepku

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.4

Angular:5.2.6

Bootstrap: 4.0

**Comment by fralewsmi** [comment]
This isn't actually a bug, just the way that JS stores Date objects.
The date is in UTC time (GMT+0). The datepicker will always show the date in local time on your front end. Call `toString()` or equivalent if you want the date displayed in local time. 
It is best practice to store Dates in UTC until you absolutely need to, because passing around a timezone-dependent value will cause problems when your app is used in other timezones

**Comment by ahmadk** [comment]
thanks so much
JSON.parse caused this problem in my code as it use as you said the UTC timezone
