### ISSUE TITLE
Tooltip with delay does not hide

### ISSUE THREAD

**Issue by vlats05** [valor-software/ngx-bootstrap#4300]
Bug description:
After clicking the button that has tooltip with delay, tooltip appears even when pointer has moved away.

How to reproduce:
1. Open https://valor-software.com/ngx-bootstrap/#/tooltip#tooltip-delay
2. Move the pointer to the "Tooltip with 0.5sec delay" button, click on it and move away in less than delay time (0.5s). As a result, tooltip appears when delay has exceeded. Tooltip must work the same way as before click. Moving the pointer away should abort the dalay.

Versions of ngx-bootstrap, Angular, and Bootstrap:
tested 2.0.2 and 2.0.4

ngx-bootstrap: 2.0.4
Angular: 4.4.6
Bootstrap: 3.3.7

Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI: 1.4.1

**Comment by valorkin** [comment]
Known issue, fix already in PR. Should land in nearest time.
Closing as duplicated issue

**Comment by mrjohnr** [comment]
same problem here,in v 3.0.1

**Comment by robvaneck** [comment]
Yep me too on ```v3.0.1```

once logged in... i display a navbar with buttons, one of them is the log-out button like below:
```
      <a class="navbar-icon"
         [routerLink]="menuItem.url"
         routerLinkActive="active"
         [tooltip]="menuItem.tooltip"
         triggers="mouseenter:mouseleave"
         [delay]="250"
         placement="right"
         container="body">
        <icon [iconName]="menuItem.icon"
              iconClass="icon-24"></icon>
      </a>
```

(note the delay 250)

now:
* I click really fast on log-out...  
* app routes to signin
* this component does not contain the navbar / thus not the button
* the tooltip is still created in the upper left corner with the html:

```
<body>
<app-root>...</app-root>
<bs-tooltip-container role="tooltip" _nghost-c16="" class="tooltip in tooltip-right bs-tooltip-right right show" style="top: -18px; left: 0px;"><div _ngcontent-c16="" class="tooltip-arrow arrow"></div><div _ngcontent-c16="" class="tooltip-inner">Log-out</div></bs-tooltip-container>
</body>
```

the error does not occur when i wait for the tooltip to show first, and then click the button. So this bug only happens when the button is clicked within the delay time... and the button is destroyed.

**Comment by batgos** [comment]
Hello,
I have also the same problem as the above comment.
When trigger elements is clicked within the delay time and destroy the tooltip appears and stay at the top left corner.
If no delay and we spam click the toolip will appears quickly at the corner but disappear directly after.
Do someone have a solution or fix ?
