### ISSUE TITLE
Modals that are shown outside of the App root component displays behind the backdrop

### ISSUE THREAD

**Issue by chrismcgregor** [valor-software/ngx-bootstrap#619]

**Comment by NZSmartie** [comment]
Unfortunately this behaviour is due to web browsers' [Stacking Context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context?redirectlocale=en-US&redirectslug=Understanding_CSS_z-index%2FThe_stacking_context). 
Essentially, a z-index inside of a element with `position: fixed` style, or with `position: absolute` or `position: relative` combined with `z-index` that's not `auto`, will create it's own stack context. In which any child element can not set a z-index that would interlace with elements outside of the stack context.

Which is why this warning is issued on Bootstrap's [Modal Documentation](https://v4-alpha.getbootstrap.com/components/modal/):

> **Modal markup placement**
> Always try to place a modal’s HTML code in a top-level position in your document to avoid other components affecting the modal’s appearance and/or functionality.

**Comment by chrismcgregor** [comment]
Thank you for the follow up.

I also have an issue trying to stack modals on top of each other (the second modal appears behind the first). Any thoughts?

Cheers!

## Chris

Christopher McGregor
415.624.6261 // chris@mcgregor.io

**Comment by valerymelou** [comment]
@chrismcgregor I don't think that nested modals are not supported yet.

**Comment by valorkin** [comment]
@chrismcgregor not supported yet, for sure
you can create an issue `request(modals): allow modals nesting`
