### ISSUE TITLE
not an issue: tsconfig.json doesn't match npm package installed

### ISSUE THREAD

**Issue by sqlsolver** [valor-software/ngx-bootstrap#737]
The /node_modules/ng2-bootstrap/tsconfig.json files section specifies the following:
  "files": [
    "./typings/index.d.ts",
    "./demo/custom-typings.d.ts",
    "./ng2-bootstrap.ts"
  ]
however in VS2015 the build fails since expected folders are missing, in fact the entire demo and typings directories are missing from the version you get when running 'npm install ng2-bootstrap' and trying 'npm install https://github.com/valor-software/ng2-bootstrap.git' results in an installation with nothing but .md files - no javascript in the component folders (and also no demo folder). The build succeeds once the files entry is removed.

**Comment by valorkin** [comment]
why do you care about tsconfig from npm?
ps: just did fresh install of ng2-bootstrap
all in place

**Comment by sqlsolver** [comment]
why do you care about tsconfig from npm?
_Because the tsconfig referencing non-existent directories causes my build to fail._

ps: just did fresh install of ng2-bootstrap
all in place
_Do you mean you added the missing demo and typings directories to your distribution?_

**Comment by valorkin** [comment]
If you want demo page you need to clone repository.

If you want to use ng2-bootstrap you don't need it

**Comment by rrfenton** [comment]
Why is this closed?  This is an actual issue.

You shouldn't be including items from your build process in the NPM module, especially if it breaks other peoples builds.

I'm encountering the same issue.  The way Visual Studio handles typescript is it parses through it's solution folder for ANY tsconfig (even folders excluded in your root level tsconfig).  Since the package includes a  tsconfig.json, with folder and file references that are NOT in the release, the packages is causing build failures for Visual Studio users.

Seeing as how these files have no use for people using the NPM package (they should only care about the *.js and *.d.ts files), why are they included at all?  There are a bunch of files that are of no help to the user at the root level of the package (tsconfig, protractor.conf, gulpfile.js, just a bunch of build stuff).

Since these files are causing build errors for some users, and are completely unneeded for the package, they should be removed from the NPM package altogether.

**Comment by dguisinger** [comment]
+1 Reopen this, it is an issue with the latest build still and Visual Studio
I just wasted an hour trying to figure out what the cause of my error messages was.

**Comment by Martin-Luft** [comment]
I have no problems with VS Code...

**Comment by Martin-Luft** [comment]
@valorkin should we exclude the `tsconfig.json` from the npm package? Would it do any harm?
