### ISSUE TITLE
tooltipClass doesn't seem to be working as intended

### ISSUE THREAD

**Issue by amnporter** [valor-software/ngx-bootstrap#767]
My markup shows 
        `<span class='glyphicon glyphicon-question-sign' [tooltip]='companyURLHelpMsg' tooltipPlacement='top' tooltipEnable='true' tooltipClass='newToolTip'></span>`

and CSS is 

```
.tooltip.newToolTip .tooltip-inner {
  background-color: $tooltip-info-bg-color;
  border: solid 2px $tooltip-info-border-color;
  color: $tooltip-info-border-color;
}

.tooltip.newToolTip .tooltip-arrow {
  border-top-color: $tooltip-info-border-color;
}
```

I cannot get the styling this way. I must target the tooltip directly in order to have styling. Am I doing something wrong or is this a bug?

**Comment by adrianfaciu** [comment]
Due to the [view encapsulation](https://angular.io/docs/ts/latest/guide/component-styles.html#!#view-encapsulation) in Angular this currently works only in two ways:
- disabling the encapsulation (ViewEncapsulation.None)
- or by specifying the style in a 'main.css' file, not associated with any component (as demonstrated in the demo usage)

For a future version I could look into making this work even if specified in the component styles.
