### ISSUE TITLE
datepicker fails 2.0.0-rc.4/1.0.24

### ISSUE THREAD

**Issue by magnayn** [valor-software/ngx-bootstrap#800]
I've seen tickets for this from a few weeks ago, but I still get the same result:

```
platform-browser.umd.js:1900 EXCEPTION: Error: Uncaught (in promise): Template parse errors:
No provider for NgModel ("-bootstrap {{ date.toDateString() }}</alert>
<div style="display:inline-block; min-height:290px">
  [ERROR ->]<datepicker [(ngModel)]="date" showWeeks="true"></datepicker>
</div>
"): Ng2BootstrapComponent@2:2


```

It doesn't seem to recognise datepicker at all, and I'm lost as to what to twiddle to fix it..

**Comment by TunaYagci** [comment]
Same here, I've been looking for an answer for 2 hours.

**Comment by koraybalci** [comment]
check out https://angular.io/docs/ts/latest/guide/forms.html if you haven't already. I had the same problem and almost made it working by adding the following bootsrapping code:

```
import { bootstrap }    from '@angular/platform-browser-dynamic';
import { disableDeprecatedForms, provideForms } from '@angular/forms';
import { AppComponent } from './app.component';
bootstrap(AppComponent, [
  disableDeprecatedForms(),
  provideForms()
 ])
 .catch((err: any) => console.error(err));
```

also, I am now importing FORM_DIRECTIVES from angular/forms instead of common and also adding 
`[ngModelOptions]="{standalone: true}"`
to all inputs I use ngModel..

Hope that helps..

**Comment by valorkin** [comment]
That's true, starting from v1.0.17 ng2-bootstrap doesn't work with deprecated forms

**Comment by whileLooper** [comment]
I'm having the same issue with pagination component,
@koraybalci what do you mean about`[ngModelOptions]="{standalone: true}"` to all inputs? 
such as: 
`<pagination  [totalItems]="bigTotalItems" [(ngModel)]="bigCurrentPage" [ngModelOptions]="{standalone: true}"></pagination>`
but I tried it, error still exist

**Comment by koraybalci** [comment]
@whileLooper yes, that's what I did, along with the other stuff I mentioned. Are you getting the same error as OP? Did you do all the pieces I mentioned?

**Comment by whileLooper** [comment]
@koraybalci 
finally I got it fixed after 2 hours research in this repo, the problem is
`import { disableDeprecatedForms, provideForms } from '@angular/forms'`
not 
`import { disableDeprecatedForms, provideForms } from '@angular/forms/index'`
can anyone tell me whats that different? import from folder and import from index file
