### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by andreo-code** [valor-software/ngx-bootstrap#859]
I am trying to install your package, but still got the same error, any information anywhere. Can I ask for help?

(index):21 Error: ReferenceError: require is not defined(…)(anonymous function) @ (index):21ZoneDelegate.invoke @ zone.js:332Zone.run @ zone.js:225(anonymous function) @ zone.js:586ZoneDelegate.invokeTask @ zone.js:365Zone.runTask @ zone.js:265drainMicroTaskQueue @ zone.js:491ZoneTask.invoke @ zone.js:435

**Comment by adrianfaciu** [comment]
We need more information in order to be able to help you. The error you pasted above does not look to be related to ng2-bootstrap, more like with the project setup. Check that everything is up and running before trying to install ng2-bootstrap.

If you have specific errors, create a small sample so we can reproduce them and see what's wrong.
