### ISSUE TITLE
fix(component helper): remove hack `get app root`

### ISSUE THREAD

**Issue by ctrl-brk** [valor-software/ngx-bootstrap#951]
RC6. Using modal component. Was working fine until I separated the application into modules. Now in lazy loaded module when I try to call .show() method I'm getting an error: `No provider for AppComponent!`

As you may guessed the AppComponent is my main/default component in the app root module. How does this modal even know about AppComponent existence?

On StackOverflow: http://stackoverflow.com/questions/39431567/angular2-ng2-bootstrap-in-lazy-loaded-module-needs-app-root-module-for-some-rea

**Comment by valorkin** [comment]
It was a hack to get root app scope, and seems it is not always working now ;(

**Comment by valorkin** [comment]
https://github.com/valor-software/ng2-bootstrap/blob/development/components/utils/components-helper.service.ts#L41-L49

**Comment by valorkin** [comment]
@ctrl-brk can you share a repo(sample) so I can test a fix?

**Comment by marcuskrahl** [comment]
@valorkin The fix does not work for me. The injector in `ComponentHelper` is of type `ElementInjector`. 

`injector.get(classOfRootComponent, false);` returns false because the AppComponent is not found. Since `ElementInjector` does not have a parent attribute, this results in an endless while loop.

Maybe there is a new way to access root components in a lazy loaded module. I tested the code with angular 2.0.0 by the way

Trying to access the AppComponent directly in the constructor of the hosting component throws an error as well. Might be an angular bug or design choice after all:

``` typescript
export class ComponentWithModal {
    constructor(private appComponent: AppComponent) {
       //throws  No provider for AppComponent!
   }
}
```

**Comment by marcuskrahl** [comment]
@valorkin I created a repository to reproduce the bug. The page freezes when trying to open a modal. It works fine if the corresponding module is not lazy loaded.

https://github.com/marcuskrahl/ng2-bootstrap-951

**Comment by valorkin** [comment]
Please try 1.1.5, it is fixed
