### ISSUE TITLE
Cannot show modal on ver 1.1.4

### ISSUE THREAD

**Issue by tungphuong** [valor-software/ngx-bootstrap#984]
Hello, i followed your sample to show modal, but browser hangs and we must kill it. It is happening on ver 1.1.4 and angular 2. Could u please check it?

Thanks,

**Comment by valorkin** [comment]
Known issue, I am on it right now

**Comment by tungphuong** [comment]
Thank, waiting for your good news

**Comment by noxborough** [comment]
already posted in #854, but will repost here as well. Since it is the same issue.

@valorkin 
Ok here goes. This plunker should demonstrate the issue. As soon as you click on the "My Modal" button, it should get caught in the infinite loop.

https://plnkr.co/edit/PLF3dN?p=info

However, if you go into my-modal.component.ts and switch from
this.myModal.config.backdrop = "static";
to
this.myModal.config.backdrop = false;
it should work.

**Comment by tungphuong** [comment]
Confirmed, It worked well. Thanks
